'use client';

import { useState, useEffect, useMemo } from 'react';
import Link from 'next/link';
import { KeyInput } from '@/components/key-input';
import { TraceViewer } from '@/components/trace-viewer';
import { LiveTelemetry } from '@/components/dashboard/live-telemetry';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

interface EncryptedTrace {
  traceId: string;
  facilitatorId?: string;
  encryptedData: string;
  aesKeyEncrypted: string;
  iv: string;
  timestamp: number;
}

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3002';

export default function DashboardPage() {
  const [privateKey, setPrivateKey] = useState<string | null>(null);
  const [facilitatorId, setFacilitatorId] = useState('');
  const [encryptedTraces, setEncryptedTraces] = useState<EncryptedTrace[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastUpdate, setLastUpdate] = useState<Date | null>(null);
  const [isConnected, setIsConnected] = useState(false);

  const liveTelemetryEnabled = Boolean(privateKey && facilitatorId);

  const loadTraces = async () => {
    if (!facilitatorId.trim()) {
      setError('Facilitator ID is required');
      setIsConnected(false);
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const response = await fetch(
        `${API_URL}/api/traces?facilitatorId=${encodeURIComponent(facilitatorId)}&limit=100`
      );

      if (!response.ok) {
        throw new Error(`Failed to load traces: ${response.statusText}`);
      }

      const data = await response.json();
      if (data.success && data.data) {
        setEncryptedTraces(data.data);
        setIsConnected(true);
        setLastUpdate(new Date());
      } else {
        setEncryptedTraces([]);
        setIsConnected(true);
        setLastUpdate(new Date());
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load traces');
      setEncryptedTraces([]);
      setIsConnected(false);
    } finally {
      setLoading(false);
    }
  };

  // Load traces automatically when both facilitator and key are present
  useEffect(() => {
    if (facilitatorId && privateKey) {
      loadTraces();
    }
  }, [facilitatorId, privateKey]);

  const keyFingerprint = useMemo(() => {
    if (!privateKey) return null;
    // lightweight fingerprint to avoid rendering the raw key in UI
    const clean = privateKey.replace(/-----.*KEY-----/g, '').replace(/\s+/g, '');
    const start = clean.slice(0, 6);
    const end = clean.slice(-6);
    return `${start}…${end}`;
  }, [privateKey]);

  if (!privateKey) {
    return (
      <div className="min-h-screen cosmic-bg relative overflow-x-hidden p-8">
        <div className="max-w-4xl mx-auto">
          <div className="mb-8">
            <h1 className="text-4xl font-bold text-white mb-2">TraceX Dashboard</h1>
            <p className="text-purple-300/70">
              Enter your private key to decrypt and view your traces
            </p>
          </div>
          <div className="mb-6 grid gap-4 md:grid-cols-2">
            <Card className="p-6 bg-gradient-to-br from-purple-950/50 to-blue-950/50 border-purple-500/30 backdrop-blur-sm">
              <h3 className="text-lg font-semibold text-white mb-2">What you need</h3>
              <ul className="list-disc list-inside text-sm text-purple-200/80 space-y-1">
                <li>RSA private key generated by the `@arturinspector/tracex-logger` SDK.</li>
                <li>Facilitator ID — your registered public key or service ID.</li>
                <li>Running TraceX backend (`NEXT_PUBLIC_API_URL`) reachable from the browser.</li>
              </ul>
            </Card>
            <Card className="p-6 bg-gradient-to-br from-purple-950/50 to-blue-950/50 border-purple-500/30 backdrop-blur-sm">
              <h3 className="text-lg font-semibold text-white mb-2">Where to find the key</h3>
              <p className="text-sm text-purple-200/80 mb-4">
                The SDK stores the private key in `.tracex-keys.json` (Node.js) or `localStorage` (browser).
                Export it locally and paste it here — nothing leaves the browser.
              </p>
              <Button
                asChild
                variant="outline"
                className="w-full border-purple-500/50 text-purple-300"
              >
                <Link href="/docs#encryption">Read the key management guide</Link>
              </Button>
            </Card>
          </div>
          <KeyInput onKeySet={setPrivateKey} />
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen cosmic-bg relative overflow-x-hidden p-8">
      <div className="max-w-7xl mx-auto space-y-6">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-white mb-2">TraceX Dashboard</h1>
          <p className="text-purple-300/70">
            View and analyze your encrypted traces
          </p>
        </div>

        <Card className="p-6 bg-gradient-to-br from-purple-950/50 to-blue-950/50 border-purple-500/30 backdrop-blur-sm">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <div className="text-sm text-purple-400/60 uppercase tracking-wide">Key status</div>
              <div className="text-white text-xl font-semibold">
                Private key is stored in browser memory only
              </div>
              <div className="text-sm text-purple-300/70 mt-1">
                Fingerprint: {keyFingerprint ?? '—'}
              </div>
            </div>
            <Badge className="bg-green-500/20 text-green-400 border-green-500/50">
              Local only
            </Badge>
          </div>
        </Card>

        {/* Facilitator ID Input + Status */}
        <Card className="p-6 bg-gradient-to-br from-purple-950/50 to-blue-950/50 border-purple-500/30 backdrop-blur-sm">
          <div className="space-y-4">
          <div className="flex flex-col md:flex-row gap-3">
            <Input
              placeholder="Enter Facilitator ID..."
              value={facilitatorId}
              onChange={(e) => setFacilitatorId(e.target.value)}
              className="bg-black/30 border-purple-500/50 text-white placeholder:text-purple-400/50 font-mono w-full"
            />
            <Button
              onClick={loadTraces}
              disabled={loading || !facilitatorId.trim()}
              className="bg-purple-600 hover:bg-purple-700 w-full md:w-auto"
            >
              {loading ? 'Loading...' : 'Load Traces'}
            </Button>
            <Button
              variant="outline"
              onClick={() => {
                setPrivateKey(null);
                setFacilitatorId('');
                setEncryptedTraces([]);
              }}
              className="border-purple-500/50 text-purple-300 w-full md:w-auto"
            >
              Change Key
            </Button>
            </div>
            
            {/* Live Status Indicators */}
            {facilitatorId && (
              <div className="flex flex-wrap items-center gap-3 text-sm">
                <div className="flex items-center gap-2">
                  <div className={`w-2 h-2 rounded-full ${isConnected ? 'bg-green-500 animate-pulse' : 'bg-red-500'}`} />
                  <span className={isConnected ? 'text-green-400' : 'text-red-400'}>
                    {isConnected ? 'Connected' : 'Disconnected'}
                  </span>
                </div>
                {lastUpdate && (
                  <div className="text-purple-400/70">
                    Last update: {lastUpdate.toLocaleTimeString()}
                  </div>
                )}
                {encryptedTraces.length > 0 && (
                  <Badge className="bg-purple-500/20 text-purple-300 border-purple-500/50">
                    {encryptedTraces.length} traces loaded
                  </Badge>
                )}
              </div>
            )}
          </div>
        </Card>

        {error && (
          <Card className="p-6 bg-gradient-to-br from-red-950/50 to-purple-950/50 border-red-500/30 backdrop-blur-sm">
            <div className="text-red-400">{error}</div>
          </Card>
        )}

        {liveTelemetryEnabled && (
          <LiveTelemetry
            privateKey={privateKey!}
            facilitatorId={facilitatorId}
            apiUrl={API_URL}
            enabled={liveTelemetryEnabled}
          />
        )}

        {encryptedTraces.length > 0 && privateKey && (
          <TraceViewer
            encryptedTraces={encryptedTraces}
            privateKey={privateKey!}
            facilitatorId={facilitatorId}
          />
        )}
      </div>
    </div>
  );
}

